import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const roboto = Roboto_Slab({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  display: "swap",
});

import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx("text-gray-700", roboto.className)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
